name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: config venv
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14
          args: config virtualenvs.in-project true
      - name: Cache venv
        uses: actions/cache@v2
        env:
          cache-name: venv
        with:
          path: .venv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: |
          poetry install
          poetry run mkdocs gh-deploy --force
